### ISSUE TITLE
Mismatch between code snippets and files in the app package

### ISSUE THREAD

**Issue by dandv** [webix-hub/gitbook-webix-jet#6]
I've downloaded and unzipped https://github.com/webix-hub/jet-start/archive/master.zip, and found that some files are very different from what's at in the [Getting Started section](https://webix.gitbook.io/webix-jet/getting-started#defining-a-view-module)

* views/top.js is complete different from the top.js at https://webix.gitbook.io/webix-jet/getting-started#defining-a-view-module
* models/records.js correctly returns a data array, but [the guide mentions a data.php file](https://webix.gitbook.io/webix-jet/getting-started#loading-data-with-models)

**Comment by kullias** [comment]
You are right, they are different.

This guide is not a description of the demo in 'jet-start', it rather describes the basic concepts:
- how you can define a view
- how you can include a subview
- how you can load data

**top.js** in the package, for example, is much longer and includes insignificant for the matter things like how to create a menu in Webix, a header template, styling. I do not think they are really necessary here. Too much code might distract attention.

In this section ([https://webix.gitbook.io/webix-jet/getting-started#defining-a-view-module](https://webix.gitbook.io/webix-jet/getting-started#defining-a-view-module)) a subview is static (not $subview:true like in the demo), because this section only tells how to define a view and how to include a static subview.

As for the model, yep, the code snippet shows a url rather than an array. This snippet shows how to get data from some URL in general. In most apps data are dynamic, I guess, so it makes sense to show where to load them instead of showing how to create a collection with local data.

Thanks for the comment, I will see to this issue and will change the chapter to make it clearer that the snippets in the text do not fully copy the code in the demo and just illustrate the things said in the text.
